name: Build GitHub Pages
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Publish to GitHubPages
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
            bun-version: latest
      - run: bun i
      - run: bun run build
      - name: Archive artifact
        shell: sh
        run: tar \
          "$RUNNER_TEMP/artifact.tar" \
          "$INPUT_PATH"
        env:
          INPUT_PATH: "dist/"
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
            name: 'github-pages'
            path: ${{ runner.temp }}/artifact.tar